fail_fast: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-json
        exclude: .vscode
      - id: end-of-file-fixer
      - id: trailing-whitespace

-   repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: ['-i']

-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v16.0.2'
    hooks:
      - id: clang-format
        exclude_types: [javascript, json]
